
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 06 22:45:30 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 5;
  public static final int CASE = 35;
  public static final int NOT_EQUAL = 10;
  public static final int CONTINUE = 31;
  public static final int LEFT_CURLY = 3;
  public static final int LESS = 13;
  public static final int FOR = 34;
  public static final int MINUS = 19;
  public static final int CHARACTER = 48;
  public static final int AND = 40;
  public static final int SEMICOLON = 6;
  public static final int OR = 39;
  public static final int BOOL = 47;
  public static final int COMMA = 8;
  public static final int INC = 37;
  public static final int DIV = 21;
  public static final int LESS_EQUAL = 14;
  public static final int RIGHT_CURLY = 4;
  public static final int PLUS = 18;
  public static final int ASSIGN = 7;
  public static final int IF = 29;
  public static final int DOT = 44;
  public static final int EOF = 0;
  public static final int GRATER_EQUAL = 12;
  public static final int RETURN = 32;
  public static final int EQUAL = 9;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int NUMBER = 46;
  public static final int MOD = 22;
  public static final int IDENT = 45;
  public static final int BREAK = 30;
  public static final int OPEN_BRACKET = 27;
  public static final int VOID = 26;
  public static final int SWITCH = 15;
  public static final int LEFT_SQUARE = 23;
  public static final int ELSE = 36;
  public static final int ENUM = 25;
  public static final int READ = 16;
  public static final int GRATER = 11;
  public static final int DOT_DOUBLE = 17;
  public static final int CLOSED_BRACKET = 28;
  public static final int PROG = 2;
  public static final int RIGHT_SQUARE = 24;
  public static final int QUESTION = 42;
  public static final int DEC = 38;
  public static final int LENGTH = 43;
  public static final int PRINT = 33;
}

